/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/authenticator/dashboard': RouteRecordInfo<'/authenticator/dashboard', '/authenticator/dashboard', Record<never, never>, Record<never, never>>,
    '/authenticator/login': RouteRecordInfo<'/authenticator/login', '/authenticator/login', Record<never, never>, Record<never, never>>,
    '/authenticator/profile': RouteRecordInfo<'/authenticator/profile', '/authenticator/profile', Record<never, never>, Record<never, never>>,
    '/authenticator/recoveryPassword': RouteRecordInfo<'/authenticator/recoveryPassword', '/authenticator/recoveryPassword', Record<never, never>, Record<never, never>>,
    '/authenticator/register': RouteRecordInfo<'/authenticator/register', '/authenticator/register', Record<never, never>, Record<never, never>>,
    '/authenticator/resetPassword': RouteRecordInfo<'/authenticator/resetPassword', '/authenticator/resetPassword', Record<never, never>, Record<never, never>>,
    '/categories/categories': RouteRecordInfo<'/categories/categories', '/categories/categories', Record<never, never>, Record<never, never>>,
    '/comments/comment': RouteRecordInfo<'/comments/comment', '/comments/comment', Record<never, never>, Record<never, never>>,
    '/coupons/coupons': RouteRecordInfo<'/coupons/coupons', '/coupons/coupons', Record<never, never>, Record<never, never>>,
    '/delivery/delivery': RouteRecordInfo<'/delivery/delivery', '/delivery/delivery', Record<never, never>, Record<never, never>>,
    '/mainpage': RouteRecordInfo<'/mainpage', '/mainpage', Record<never, never>, Record<never, never>>,
    '/menagementPage/pages': RouteRecordInfo<'/menagementPage/pages', '/menagementPage/pages', Record<never, never>, Record<never, never>>,
    '/menagementPage/pageView/[id]': RouteRecordInfo<'/menagementPage/pageView/[id]', '/menagementPage/pageView/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/notifications/notify': RouteRecordInfo<'/notifications/notify', '/notifications/notify', Record<never, never>, Record<never, never>>,
    '/orders/orders': RouteRecordInfo<'/orders/orders', '/orders/orders', Record<never, never>, Record<never, never>>,
    '/payments/payments': RouteRecordInfo<'/payments/payments', '/payments/payments', Record<never, never>, Record<never, never>>,
    '/products/ProductForm': RouteRecordInfo<'/products/ProductForm', '/products/ProductForm', Record<never, never>, Record<never, never>>,
    '/products/products': RouteRecordInfo<'/products/products', '/products/products', Record<never, never>, Record<never, never>>,
    '/products/productView/[slug]': RouteRecordInfo<'/products/productView/[slug]', '/products/productView/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/seo/seo': RouteRecordInfo<'/seo/seo', '/seo/seo', Record<never, never>, Record<never, never>>,
    '/stock/stock': RouteRecordInfo<'/stock/stock', '/stock/stock', Record<never, never>, Record<never, never>>,
  }
}
