/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/adBanner/adBanner': RouteRecordInfo<'/adBanner/adBanner', '/adBanner/adBanner', Record<never, never>, Record<never, never>>,
    '/authenticator/client/clientDashboard': RouteRecordInfo<'/authenticator/client/clientDashboard', '/authenticator/client/clientDashboard', Record<never, never>, Record<never, never>>,
    '/authenticator/client/clientLogin': RouteRecordInfo<'/authenticator/client/clientLogin', '/authenticator/client/clientLogin', Record<never, never>, Record<never, never>>,
    '/authenticator/client/clientRegister': RouteRecordInfo<'/authenticator/client/clientRegister', '/authenticator/client/clientRegister', Record<never, never>, Record<never, never>>,
    '/authenticator/client/profile/editProfileDialog': RouteRecordInfo<'/authenticator/client/profile/editProfileDialog', '/authenticator/client/profile/editProfileDialog', Record<never, never>, Record<never, never>>,
    '/authenticator/client/profileClient': RouteRecordInfo<'/authenticator/client/profileClient', '/authenticator/client/profileClient', Record<never, never>, Record<never, never>>,
    '/authenticator/dashboard': RouteRecordInfo<'/authenticator/dashboard', '/authenticator/dashboard', Record<never, never>, Record<never, never>>,
    '/authenticator/login': RouteRecordInfo<'/authenticator/login', '/authenticator/login', Record<never, never>, Record<never, never>>,
    '/authenticator/profile': RouteRecordInfo<'/authenticator/profile', '/authenticator/profile', Record<never, never>, Record<never, never>>,
    '/authenticator/recoveryPassword': RouteRecordInfo<'/authenticator/recoveryPassword', '/authenticator/recoveryPassword', Record<never, never>, Record<never, never>>,
    '/authenticator/register': RouteRecordInfo<'/authenticator/register', '/authenticator/register', Record<never, never>, Record<never, never>>,
    '/authenticator/resetPassword': RouteRecordInfo<'/authenticator/resetPassword', '/authenticator/resetPassword', Record<never, never>, Record<never, never>>,
    '/blog/blogForm': RouteRecordInfo<'/blog/blogForm', '/blog/blogForm', Record<never, never>, Record<never, never>>,
    '/blog/blogs': RouteRecordInfo<'/blog/blogs', '/blog/blogs', Record<never, never>, Record<never, never>>,
    '/blog/blogView/[slug]': RouteRecordInfo<'/blog/blogView/[slug]', '/blog/blogView/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/blog/blogView/comments': RouteRecordInfo<'/blog/blogView/comments', '/blog/blogView/comments', Record<never, never>, Record<never, never>>,
    '/cart/client/cartClient': RouteRecordInfo<'/cart/client/cartClient', '/cart/client/cartClient', Record<never, never>, Record<never, never>>,
    '/categories/categories': RouteRecordInfo<'/categories/categories', '/categories/categories', Record<never, never>, Record<never, never>>,
    '/comments/client/commentForm': RouteRecordInfo<'/comments/client/commentForm', '/comments/client/commentForm', Record<never, never>, Record<never, never>>,
    '/comments/comment': RouteRecordInfo<'/comments/comment', '/comments/comment', Record<never, never>, Record<never, never>>,
    '/comments/commentsView/commentInputForm': RouteRecordInfo<'/comments/commentsView/commentInputForm', '/comments/commentsView/commentInputForm', Record<never, never>, Record<never, never>>,
    '/comments/commentsView/reportComment': RouteRecordInfo<'/comments/commentsView/reportComment', '/comments/commentsView/reportComment', Record<never, never>, Record<never, never>>,
    '/coupons/client/clientCoupons': RouteRecordInfo<'/coupons/client/clientCoupons', '/coupons/client/clientCoupons', Record<never, never>, Record<never, never>>,
    '/coupons/coupons': RouteRecordInfo<'/coupons/coupons', '/coupons/coupons', Record<never, never>, Record<never, never>>,
    '/delivery/delivery': RouteRecordInfo<'/delivery/delivery', '/delivery/delivery', Record<never, never>, Record<never, never>>,
    '/mainpage': RouteRecordInfo<'/mainpage', '/mainpage', Record<never, never>, Record<never, never>>,
    '/menagementPage/pages': RouteRecordInfo<'/menagementPage/pages', '/menagementPage/pages', Record<never, never>, Record<never, never>>,
    '/menagementPage/pageView/[id]': RouteRecordInfo<'/menagementPage/pageView/[id]', '/menagementPage/pageView/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/notifications/notify': RouteRecordInfo<'/notifications/notify', '/notifications/notify', Record<never, never>, Record<never, never>>,
    '/orders/client/clientOrders': RouteRecordInfo<'/orders/client/clientOrders', '/orders/client/clientOrders', Record<never, never>, Record<never, never>>,
    '/orders/orders': RouteRecordInfo<'/orders/orders', '/orders/orders', Record<never, never>, Record<never, never>>,
    '/payments/client/checkout': RouteRecordInfo<'/payments/client/checkout', '/payments/client/checkout', Record<never, never>, Record<never, never>>,
    '/payments/client/payment_result': RouteRecordInfo<'/payments/client/payment_result', '/payments/client/payment_result', Record<never, never>, Record<never, never>>,
    '/payments/payments': RouteRecordInfo<'/payments/payments', '/payments/payments', Record<never, never>, Record<never, never>>,
    '/products/ProductForm': RouteRecordInfo<'/products/ProductForm', '/products/ProductForm', Record<never, never>, Record<never, never>>,
    '/products/products': RouteRecordInfo<'/products/products', '/products/products', Record<never, never>, Record<never, never>>,
    '/products/productView/[slug]': RouteRecordInfo<'/products/productView/[slug]', '/products/productView/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/seo/seo': RouteRecordInfo<'/seo/seo', '/seo/seo', Record<never, never>, Record<never, never>>,
    '/stock/stock': RouteRecordInfo<'/stock/stock', '/stock/stock', Record<never, never>, Record<never, never>>,
  }
}
