/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/authenticator/dashboard': RouteRecordInfo<'/authenticator/dashboard', '/authenticator/dashboard', Record<never, never>, Record<never, never>>,
    '/authenticator/login': RouteRecordInfo<'/authenticator/login', '/authenticator/login', Record<never, never>, Record<never, never>>,
    '/authenticator/profile': RouteRecordInfo<'/authenticator/profile', '/authenticator/profile', Record<never, never>, Record<never, never>>,
    '/authenticator/register': RouteRecordInfo<'/authenticator/register', '/authenticator/register', Record<never, never>, Record<never, never>>,
    '/categories/categories': RouteRecordInfo<'/categories/categories', '/categories/categories', Record<never, never>, Record<never, never>>,
  }
}
